# ------------------- 2023
constructorColors = {'Red Bull': '#15185F',
                     'Aston Martin': '#00594F',
                     'Mercedes': '#00A19C',
                     'Ferrari': '#FF0200',
                     'McLaren': '#FE8001',
                     'Alpine F1 Team': '#0C1D2C',
                     'Haas F1 Team': '#E1050B',
                     'Alfa Romeo': '#A50E2D',
                     'AlphaTauri': '#032947',
                     'Williams': '#03A0DE',
                     'Racing Point': '#F493C6',
                     'Renault': '#F2B502',
                     'Toro Rosso': '#032EAD',
                     'Force India': '#FF810D',
                     'Sauber': '#570016',
                     'Manor Marussia': '#E55A19',
                     'Lotus F1': '#062A25',
                     'Caterham': '#014A2F',
                     'Marussia': '#E55A19',
                     'HRT': '#A6904F',
                     'Virgin': '#B40D02',
                     }
# -------------------

