#------------------- 2023
driversId2023 = {'alonso':'Alonso',
                 'perez':'Perez',
                 'russell':'Russell',
                 'stroll':'Stroll',
                 'sainz':'Sainz',
                 'ocon':'Ocon',
                 'hamilton':'Hamilton',
                 'gasly':'Gasly',
                 'leclerc':'Leclerc',
                 'zhou':'Zhou',
                 'kevin_magnussen':'Magnussen',
                 'hulkenberg':'Hulkenberg',
                 'max_verstappen':'Verstappen',
                 'tsunoda':'Tsunoda',
                 'bottas':'Bottas',
                 'albon':'Albon',
                 'norris':'Norris',
                 'de_vries':'De Vries',
                 'piastri':'Piastri',
                 'sargeant':'Sargeant'}

constructorColor2023 = {'Red Bull': '#15185F',
                         'Aston Martin':'#00594F',
                         'Mercedes': '#00A19C',
                         'Ferrari': '#FF0200',
                         'McLaren': '#FE8001',
                         'Alpine F1 Team': '#0C1D2C',
                         'Haas F1 Team': '#E1050B',
                         'Alfa Romeo': '#A50E2D',
                         'AlphaTauri': '#032947',
                         'Williams': '#001B54'}

driverColor2023 = {'Verstappen': '#15185F',
                   'Perez': '#15185F',
                   'Alonso': '#00594F',
                   'Stroll': '#00594F',
                   'Hamilton': '#00A19C',
                   'Russell': '#00A19C',
                   'Leclerc': '#FF0200',
                   'Sainz': '#FF0200',
                   'Piastri': '#FE8001',
                   'Norris': '#FE8001',
                   'Ocon': '#0643A0',
                   'Gasly': '#0643A0',
                   'Hulkenberg': '#351818',
                   'Magnussen': '#351818',
                   'Bottas': '#A50E2D',
                   'Zhou': '#A50E2D',
                   'Tsunoda': '#18344d',
                   'De Vries': '#18344d',
                   'Sargeant': '#001B54',
                   'Albon': '#001B54'}
#-------------------